{
 "title": "throughput",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS (all producers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(http_server_request_duration_seconds_count{job=\"MySqlEndToEndPollingSample.Producer\"}[$__rate_interval]))",
     "legendFormat": "producer {{instance}}"
    }
   ]
  },
  {
   "title": "RPS (by producer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(http_server_request_duration_seconds_count{job=\"MySqlEndToEndPollingSample.Producer\"}[$__rate_interval])",
     "legendFormat": "producer {{instance}}"
    }
   ]
  },
  {
   "title": "Messages produced per second (all producers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_producer_produced_messages_total{job=\"MySqlEndToEndPollingSample.Producer\"}[$__rate_interval]))",
     "legendFormat": "producer"
    }
   ]
  },
  {
   "title": "Messages produced per second (by producer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(rabbitmq_producer_produced_messages_total{job=\"MySqlEndToEndPollingSample.Producer\"}[$__rate_interval])",
     "legendFormat": "producer {{instance}}"
    }
   ]
  },
  {
   "title": "Messages batches produced per second (all producers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(outbox_produced_batches_total{job=\"MySqlEndToEndPollingSample.Producer\"}[$__rate_interval]))",
     "legendFormat": "producer"
    }
   ]
  },
  {
   "title": "Messages batches produced per second (by producer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "irate(outbox_produced_batches_total{job=\"MySqlEndToEndPollingSample.Producer\"}[$__rate_interval])",
     "legendFormat": "producer {{instance}}"
    }
   ]
  },
  {
   "title": "Messages consumed per second (all consumers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_consumer_consumed_messages_total{job=\"MySqlEndToEndPollingSample.Consumer\"}[$__rate_interval]))",
     "legendFormat": "consumer {{instance}}"
    }
   ]
  },
  {
   "title": "Messages consumed per second (by consumer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "irate(rabbitmq_consumer_consumed_messages_total{job=\"MySqlEndToEndPollingSample.Consumer\"}[$__rate_interval])",
     "legendFormat": "consumer {{instance}}"
    }
   ]
  }
 ]
}