[build.environment]
  NODE_VERSION = "22"

[build]
    publish = "docs/.vitepress/dist"
    command = "npm run docs:build"

[context.production.environment]
    ENABLE_ANALYTICS = "true"

# Plausible proxy - https://plausible.io/docs/proxy/introduction & https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
from = "/p/js/script.js"
to = "https://plausible.io/js/script.js"
status = 200
force = true

# Plausible proxy - https://plausible.io/docs/proxy/introduction & https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
from = "/p/api/event"
to = "https://plausible.io/api/event"
status = 200
force = true