name: Publish Release
on:
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
            11.0.x

      - name: Build & Test
        uses: cake-build/cake-action@d218f1133bb74a1df0b08c89cfd8fc100c09e1a0 # v3.0.1
        with:
          file-path: build/CakeRunner.cs
          target: BuildAndTest

      - name: Package & Push
        uses: cake-build/cake-action@d218f1133bb74a1df0b08c89cfd8fc100c09e1a0 # v3.0.1
        with:
          file-path: build/CakeRunner.cs
          target: PackageAndPush
          arguments: |
            source: "https://api.nuget.org/v3/index.json"
            allow-nightly: false
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
